/*
 * DataForSEO API documentation
 * DataForSEO API is the starting point on your journey towards building powerful SEO software. With DataForSEO you can get all the data you need to build an efficient application while also saving your time and budget. DataForSEO API is using the REST technology for interchanging data between your application and our service. The data exchange is made through the widely used HTTP protocol, which allows applying our API to almost all programming languages.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.dataforseo.dataforseo_client.api;

import io.github.dataforseo.dataforseo_client.ApiException;
import io.github.dataforseo.dataforseo_client.model.ContentGenerationCheckGrammarLanguagesResponseInfo;
import io.github.dataforseo.dataforseo_client.model.ContentGenerationCheckGrammarLiveRequestInfo;
import io.github.dataforseo.dataforseo_client.model.ContentGenerationCheckGrammarLiveResponseInfo;
import io.github.dataforseo.dataforseo_client.model.ContentGenerationGenerateLiveRequestInfo;
import io.github.dataforseo.dataforseo_client.model.ContentGenerationGenerateLiveResponseInfo;
import io.github.dataforseo.dataforseo_client.model.ContentGenerationGenerateMetaTagsLiveRequestInfo;
import io.github.dataforseo.dataforseo_client.model.ContentGenerationGenerateMetaTagsLiveResponseInfo;
import io.github.dataforseo.dataforseo_client.model.ContentGenerationGenerateSubTopicsLiveRequestInfo;
import io.github.dataforseo.dataforseo_client.model.ContentGenerationGenerateSubTopicsLiveResponseInfo;
import io.github.dataforseo.dataforseo_client.model.ContentGenerationGenerateTextLiveRequestInfo;
import io.github.dataforseo.dataforseo_client.model.ContentGenerationGenerateTextLiveResponseInfo;
import io.github.dataforseo.dataforseo_client.model.ContentGenerationGrammarRulesResponseInfo;
import io.github.dataforseo.dataforseo_client.model.ContentGenerationParaphraseLiveRequestInfo;
import io.github.dataforseo.dataforseo_client.model.ContentGenerationParaphraseLiveResponseInfo;
import io.github.dataforseo.dataforseo_client.model.ContentGenerationTextSummaryLanguagesResponseInfo;
import io.github.dataforseo.dataforseo_client.model.ContentGenerationTextSummaryLiveRequestInfo;
import io.github.dataforseo.dataforseo_client.model.ContentGenerationTextSummaryLiveResponseInfo;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ContentGenerationApi
 */
@Disabled
public class ContentGenerationApiTest {

    private final ContentGenerationApi api = new ContentGenerationApi();

    /**
     * ‌ This endpoint will provide you with grammar and spelling corrections for the text you specify. for more info please visit &#39;https://docs.dataforseo.com/v3/content_generation/check_grammar/live/?bash&#39;
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void checkGrammarLiveTest() throws ApiException {
        List<ContentGenerationCheckGrammarLiveRequestInfo> contentGenerationCheckGrammarLiveRequestInfo = null;
        ContentGenerationCheckGrammarLiveResponseInfo response = api.checkGrammarLive(contentGenerationCheckGrammarLiveRequestInfo);
        // TODO: test validations
    }

    /**
     * You will receive the list of languages by calling this API.   As a response of the API server, you will receive JSON-encoded data containing a tasks array with the information specific to the set tasks. for more info please visit &#39;https://docs.dataforseo.com/v3/content_generation/check_grammar/languages/?bash&#39;
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void contentGenerationCheckGrammarLanguagesTest() throws ApiException {
        ContentGenerationCheckGrammarLanguagesResponseInfo response = api.contentGenerationCheckGrammarLanguages();
        // TODO: test validations
    }

    /**
     * You will receive the list of languages by calling this API.   As a response of the API server, you will receive JSON-encoded data containing a tasks array with the information specific to the set tasks. for more info please visit &#39;https://docs.dataforseo.com/v3/content_generation/text_summary/languages/?bash&#39;
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void contentGenerationTextSummaryLanguagesTest() throws ApiException {
        ContentGenerationTextSummaryLanguagesResponseInfo response = api.contentGenerationTextSummaryLanguages();
        // TODO: test validations
    }

    /**
     * ‌ This endpoint will provide you with a text generated based on the part of the text you define and other available parameters. for more info please visit &#39;https://docs.dataforseo.com/v3/content_generation/generate/live/?bash&#39;
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void generateLiveTest() throws ApiException {
        List<ContentGenerationGenerateLiveRequestInfo> contentGenerationGenerateLiveRequestInfo = null;
        ContentGenerationGenerateLiveResponseInfo response = api.generateLive(contentGenerationGenerateLiveRequestInfo);
        // TODO: test validations
    }

    /**
     * ‌ This endpoint is designed to generate title and description meta tags for a text specified in the request. for more info please visit &#39;https://docs.dataforseo.com/v3/content_generation/generate_meta_tags/live/?bash&#39;
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void generateMetaTagsLiveTest() throws ApiException {
        List<ContentGenerationGenerateMetaTagsLiveRequestInfo> contentGenerationGenerateMetaTagsLiveRequestInfo = null;
        ContentGenerationGenerateMetaTagsLiveResponseInfo response = api.generateMetaTagsLive(contentGenerationGenerateMetaTagsLiveRequestInfo);
        // TODO: test validations
    }

    /**
     * ‌ This endpoint will provide you with 10 subtopics generated based on the topic and other parameters you specify. for more info please visit &#39;https://docs.dataforseo.com/v3/content_generation/generate_sub_topics/live/?bash&#39;
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void generateSubTopicsLiveTest() throws ApiException {
        List<ContentGenerationGenerateSubTopicsLiveRequestInfo> contentGenerationGenerateSubTopicsLiveRequestInfo = null;
        ContentGenerationGenerateSubTopicsLiveResponseInfo response = api.generateSubTopicsLive(contentGenerationGenerateSubTopicsLiveRequestInfo);
        // TODO: test validations
    }

    /**
     * ‌ This endpoint will provide you with a text generated based on the topic and other parameters you specify. for more info please visit &#39;https://docs.dataforseo.com/v3/content_generation/generate_text/live/?bash&#39;
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void generateTextLiveTest() throws ApiException {
        List<ContentGenerationGenerateTextLiveRequestInfo> contentGenerationGenerateTextLiveRequestInfo = null;
        ContentGenerationGenerateTextLiveResponseInfo response = api.generateTextLive(contentGenerationGenerateTextLiveRequestInfo);
        // TODO: test validations
    }

    /**
     * You will receive the list of grammar rules by calling this API.   As a response of the API server, you will receive JSON-encoded data containing a tasks array with the information specific to the set tasks. for more info please visit &#39;https://docs.dataforseo.com/v3/content_generation/grammar_rules/?bash&#39;
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void grammarRulesTest() throws ApiException {
        ContentGenerationGrammarRulesResponseInfo response = api.grammarRules();
        // TODO: test validations
    }

    /**
     * ‌ This endpoint will provide you with a paraphrased version of the text you specify. for more info please visit &#39;https://docs.dataforseo.com/v3/content_generation/paraphrase/live/?bash&#39;
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void paraphraseLiveTest() throws ApiException {
        List<ContentGenerationParaphraseLiveRequestInfo> contentGenerationParaphraseLiveRequestInfo = null;
        ContentGenerationParaphraseLiveResponseInfo response = api.paraphraseLive(contentGenerationParaphraseLiveRequestInfo);
        // TODO: test validations
    }

    /**
     * ‌ This endpoint will provide you with statistical data based on the given text, such as the number of words and sentences, vocabulary density, and text readability. for more info please visit &#39;https://docs.dataforseo.com/v3/content_generation/text_summary/live/?bash&#39;
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void textSummaryLiveTest() throws ApiException {
        List<ContentGenerationTextSummaryLiveRequestInfo> contentGenerationTextSummaryLiveRequestInfo = null;
        ContentGenerationTextSummaryLiveResponseInfo response = api.textSummaryLive(contentGenerationTextSummaryLiveRequestInfo);
        // TODO: test validations
    }

}
