/*
 * DataForSEO API documentation
 * DataForSEO API is the starting point on your journey towards building powerful SEO software. With DataForSEO you can get all the data you need to build an efficient application while also saving your time and budget. DataForSEO API is using the REST technology for interchanging data between your application and our service. The data exchange is made through the widely used HTTP protocol, which allows applying our API to almost all programming languages.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.dataforseo.dataforseo_client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ContentGenerationCheckGrammarLiveItem
 */
public class ContentGenerationCheckGrammarLiveItemTest {
    private final ContentGenerationCheckGrammarLiveItem model = new ContentGenerationCheckGrammarLiveItem();

    /**
     * Model tests for ContentGenerationCheckGrammarLiveItem
     */
    @Test
    public void testContentGenerationCheckGrammarLiveItem() {
        // TODO: test ContentGenerationCheckGrammarLiveItem
    }

    /**
     * Test the property 'message'
     */
    @Test
    public void messageTest() {
        // TODO: test message
    }

    /**
     * Test the property 'description'
     */
    @Test
    public void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'suggestions'
     */
    @Test
    public void suggestionsTest() {
        // TODO: test suggestions
    }

    /**
     * Test the property 'offset'
     */
    @Test
    public void offsetTest() {
        // TODO: test offset
    }

    /**
     * Test the property 'length'
     */
    @Test
    public void lengthTest() {
        // TODO: test length
    }

    /**
     * Test the property 'type'
     */
    @Test
    public void typeTest() {
        // TODO: test type
    }

    /**
     * Test the property 'ruleId'
     */
    @Test
    public void ruleIdTest() {
        // TODO: test ruleId
    }

    /**
     * Test the property 'ruleDescription'
     */
    @Test
    public void ruleDescriptionTest() {
        // TODO: test ruleDescription
    }

    /**
     * Test the property 'ruleIssueType'
     */
    @Test
    public void ruleIssueTypeTest() {
        // TODO: test ruleIssueType
    }

    /**
     * Test the property 'ruleCategoryId'
     */
    @Test
    public void ruleCategoryIdTest() {
        // TODO: test ruleCategoryId
    }

    /**
     * Test the property 'ruleCategoryName'
     */
    @Test
    public void ruleCategoryNameTest() {
        // TODO: test ruleCategoryName
    }

}
