/*
 * DataForSEO API documentation
 * DataForSEO API is the starting point on your journey towards building powerful SEO software. With DataForSEO you can get all the data you need to build an efficient application while also saving your time and budget. DataForSEO API is using the REST technology for interchanging data between your application and our service. The data exchange is made through the widely used HTTP protocol, which allows applying our API to almost all programming languages.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.dataforseo.dataforseo_client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.github.dataforseo.dataforseo_client.model.BacklinksInfo;
import io.github.dataforseo.dataforseo_client.model.MetricsBundleInfo;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for DomainAnalyticsWhoisOverviewLiveItem
 */
public class DomainAnalyticsWhoisOverviewLiveItemTest {
    private final DomainAnalyticsWhoisOverviewLiveItem model = new DomainAnalyticsWhoisOverviewLiveItem();

    /**
     * Model tests for DomainAnalyticsWhoisOverviewLiveItem
     */
    @Test
    public void testDomainAnalyticsWhoisOverviewLiveItem() {
        // TODO: test DomainAnalyticsWhoisOverviewLiveItem
    }

    /**
     * Test the property 'domain'
     */
    @Test
    public void domainTest() {
        // TODO: test domain
    }

    /**
     * Test the property 'createdDatetime'
     */
    @Test
    public void createdDatetimeTest() {
        // TODO: test createdDatetime
    }

    /**
     * Test the property 'changedDatetime'
     */
    @Test
    public void changedDatetimeTest() {
        // TODO: test changedDatetime
    }

    /**
     * Test the property 'expirationDatetime'
     */
    @Test
    public void expirationDatetimeTest() {
        // TODO: test expirationDatetime
    }

    /**
     * Test the property 'updatedDatetime'
     */
    @Test
    public void updatedDatetimeTest() {
        // TODO: test updatedDatetime
    }

    /**
     * Test the property 'firstSeen'
     */
    @Test
    public void firstSeenTest() {
        // TODO: test firstSeen
    }

    /**
     * Test the property 'eppStatusCodes'
     */
    @Test
    public void eppStatusCodesTest() {
        // TODO: test eppStatusCodes
    }

    /**
     * Test the property 'tld'
     */
    @Test
    public void tldTest() {
        // TODO: test tld
    }

    /**
     * Test the property 'registered'
     */
    @Test
    public void registeredTest() {
        // TODO: test registered
    }

    /**
     * Test the property 'registrar'
     */
    @Test
    public void registrarTest() {
        // TODO: test registrar
    }

    /**
     * Test the property 'metrics'
     */
    @Test
    public void metricsTest() {
        // TODO: test metrics
    }

    /**
     * Test the property 'backlinksInfo'
     */
    @Test
    public void backlinksInfoTest() {
        // TODO: test backlinksInfo
    }

}
