/*
 * DataForSEO API documentation
 * DataForSEO API is the starting point on your journey towards building powerful SEO software. With DataForSEO you can get all the data you need to build an efficient application while also saving your time and budget. DataForSEO API is using the REST technology for interchanging data between your application and our service. The data exchange is made through the widely used HTTP protocol, which allows applying our API to almost all programming languages.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.dataforseo.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.dataforseo.client.model.AmazonDeliveryInfo;
import org.dataforseo.client.model.BaseAmazonSerpElementItem;
import org.dataforseo.client.model.RatingElement;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for AmazonAmazonPaidSerpElementItem
 */
public class AmazonAmazonPaidSerpElementItemTest {
    private final AmazonAmazonPaidSerpElementItem model = new AmazonAmazonPaidSerpElementItem();

    /**
     * Model tests for AmazonAmazonPaidSerpElementItem
     */
    @Test
    public void testAmazonAmazonPaidSerpElementItem() {
        // TODO: test AmazonAmazonPaidSerpElementItem
    }

    /**
     * Test the property 'type'
     */
    @Test
    public void typeTest() {
        // TODO: test type
    }

    /**
     * Test the property 'rankGroup'
     */
    @Test
    public void rankGroupTest() {
        // TODO: test rankGroup
    }

    /**
     * Test the property 'rankAbsolute'
     */
    @Test
    public void rankAbsoluteTest() {
        // TODO: test rankAbsolute
    }

    /**
     * Test the property 'xpath'
     */
    @Test
    public void xpathTest() {
        // TODO: test xpath
    }

    /**
     * Test the property 'domain'
     */
    @Test
    public void domainTest() {
        // TODO: test domain
    }

    /**
     * Test the property 'title'
     */
    @Test
    public void titleTest() {
        // TODO: test title
    }

    /**
     * Test the property 'url'
     */
    @Test
    public void urlTest() {
        // TODO: test url
    }

    /**
     * Test the property 'imageUrl'
     */
    @Test
    public void imageUrlTest() {
        // TODO: test imageUrl
    }

    /**
     * Test the property 'boughtPastMonth'
     */
    @Test
    public void boughtPastMonthTest() {
        // TODO: test boughtPastMonth
    }

    /**
     * Test the property 'priceFrom'
     */
    @Test
    public void priceFromTest() {
        // TODO: test priceFrom
    }

    /**
     * Test the property 'priceTo'
     */
    @Test
    public void priceToTest() {
        // TODO: test priceTo
    }

    /**
     * Test the property 'currency'
     */
    @Test
    public void currencyTest() {
        // TODO: test currency
    }

    /**
     * Test the property 'specialOffers'
     */
    @Test
    public void specialOffersTest() {
        // TODO: test specialOffers
    }

    /**
     * Test the property 'dataAsin'
     */
    @Test
    public void dataAsinTest() {
        // TODO: test dataAsin
    }

    /**
     * Test the property 'rating'
     */
    @Test
    public void ratingTest() {
        // TODO: test rating
    }

    /**
     * Test the property 'isAmazonChoice'
     */
    @Test
    public void isAmazonChoiceTest() {
        // TODO: test isAmazonChoice
    }

    /**
     * Test the property 'isBestSeller'
     */
    @Test
    public void isBestSellerTest() {
        // TODO: test isBestSeller
    }

    /**
     * Test the property 'deliveryInfo'
     */
    @Test
    public void deliveryInfoTest() {
        // TODO: test deliveryInfo
    }

}
