/*
 * DataForSEO API documentation
 * DataForSEO API is the starting point on your journey towards building powerful SEO software. With DataForSEO you can get all the data you need to build an efficient application while also saving your time and budget. DataForSEO API is using the REST technology for interchanging data between your application and our service. The data exchange is made through the widely used HTTP protocol, which allows applying our API to almost all programming languages.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.dataforseo.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.dataforseo.client.model.BaseOnPageResourceItemInfo;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for OnPageWaterfallItem
 */
public class OnPageWaterfallItemTest {
    private final OnPageWaterfallItem model = new OnPageWaterfallItem();

    /**
     * Model tests for OnPageWaterfallItem
     */
    @Test
    public void testOnPageWaterfallItem() {
        // TODO: test OnPageWaterfallItem
    }

    /**
     * Test the property 'pageUrl'
     */
    @Test
    public void pageUrlTest() {
        // TODO: test pageUrl
    }

    /**
     * Test the property 'timeToInteractive'
     */
    @Test
    public void timeToInteractiveTest() {
        // TODO: test timeToInteractive
    }

    /**
     * Test the property 'domComplete'
     */
    @Test
    public void domCompleteTest() {
        // TODO: test domComplete
    }

    /**
     * Test the property 'connectionTime'
     */
    @Test
    public void connectionTimeTest() {
        // TODO: test connectionTime
    }

    /**
     * Test the property 'timeToSecureConnection'
     */
    @Test
    public void timeToSecureConnectionTest() {
        // TODO: test timeToSecureConnection
    }

    /**
     * Test the property 'requestSentTime'
     */
    @Test
    public void requestSentTimeTest() {
        // TODO: test requestSentTime
    }

    /**
     * Test the property 'waitingTime'
     */
    @Test
    public void waitingTimeTest() {
        // TODO: test waitingTime
    }

    /**
     * Test the property 'downloadTime'
     */
    @Test
    public void downloadTimeTest() {
        // TODO: test downloadTime
    }

    /**
     * Test the property 'durationTime'
     */
    @Test
    public void durationTimeTest() {
        // TODO: test durationTime
    }

    /**
     * Test the property 'fetchStart'
     */
    @Test
    public void fetchStartTest() {
        // TODO: test fetchStart
    }

    /**
     * Test the property 'fetchEnd'
     */
    @Test
    public void fetchEndTest() {
        // TODO: test fetchEnd
    }

    /**
     * Test the property 'resources'
     */
    @Test
    public void resourcesTest() {
        // TODO: test resources
    }

}
